#!/bin/bash
set -e
set -x

CADMIUMROOT=$(dirname $(dirname $(dirname $(realpath $0))))
DESTDIR=$1

. $CADMIUMROOT/config
mkdir -p "$CADMIUMROOT/tmp"
ROOTFS_TAR="https://cdimage.ubuntu.com/cdimage/ubuntu-base/$SUITE/daily/current/$SUITE-base-arm64.tar.gz"
if [ ! -f "$CADMIUMROOT/tmp/ubuntu-rootfs-$ARCH_ALARM.tar.gz" ]; then
	rm $CADMIUMROOT/tmp/ubuntu-rootfs-$ARCH_ALARM.tar.gz || true
	wget "$ROOTFS_TAR" -O $CADMIUMROOT/tmp/ubuntu-rootfs-$ARCH_ALARM.tar.gz
fi
tar xfp $CADMIUMROOT/tmp/ubuntu-rootfs-${ARCH_ALARM}.tar.gz -C $DESTDIR


rm $DESTDIR/etc/resolv.conf # resolv.conf -> /run/systemd/resolve/resolv.conf not working in $chroot
echo "nameserver 1.1.1.1" > $DESTDIR/etc/resolv.conf # TODO: make it configurable or fetch from host?


chroot "$DESTDIR" /usr/bin/apt update
#chroot $DESTDIR /usr/bin/apt install -y dialog vim f2fs-tools libudev-dev build-essential git parted


